---
abstract: 'Runs view output through PDF::Boxer and sets response content-type if not already set.'
author:
  - 'Jason Galea <lecstor@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::View::TT: 0
  FindBin: 0
  Moose: 0
  Path::Class: 0
  Test::More: 0
  base: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-PDFBoxer
requires:
  Moose::Role: 0
  PDF::Boxer: 0.003
  PDF::Boxer::SpecParser: 0
  namespace::clean: 0
version: 0.001
